-- FlutterKaigiスタッフメンバーのシードデータ
WITH
    timestamp AS (
        SELECT
            '2025-06-01 00:00:00'::timestamp AS ts
    )
INSERT INTO
    public.staff_members (name, icon_name, greeting, created_at, updated_at)
SELECT
    name,
    icon_name,
    CASE WHEN greeting = '' THEN NULL ELSE greeting END,
    ts,
    ts
FROM
    (
        VALUES
            ('kuno', '752792bf-203f-4070-6292-0d468bfd2997.webp', '盛り上げていきマッショイ！！！！！！！！！！！！！！！'),
            ('CardsEditor', '6696bd31-1184-cccf-694c-35a73dbe99c8.webp', ''),
            ('ENDO Takumi', 'ca3e78a7-8afd-4e92-bb90-77b0878c3348.webp', ''),
            ('白崎 紀充', 'bdfd4ab5-5411-6740-b046-78fdcdde9e7b.webp', ''),
            ('m.kosuke', 'a6b121ee-ff62-b436-d7d4-dd799fd67692.webp', 'フロサポ🐬'),
            ('Sohichiro/そーちゃん', '261f9261-b64e-f717-431d-82f8cce5ca4c.webp', '今年もやっていき！'),
            ('おかやまん', 'edaa85c5-d9dd-9dad-9516-849059f2d9a4.webp', '開発楽しむ！'),
            ('ちっぴー', 'faac06be-6646-90fe-d3c2-db95783ffa8a.webp', 'アプリの人として頑張ります。'),
            ('もぐもぐ', '2fd456f6-20e9-0733-883d-6b25b82f75c5.webp', '2025年もよろしくお願いします!'),
            ('jiyuujin', 'dbc18436-e245-7c5f-8a11-7510a6567d01.webp', ''),
            ('うめちゃん', 'a344dd22-91fe-c805-4951-c61133368364.webp', '参加者の皆さんが楽しめる会になるように頑張ります！'),
            ('たっつー', 'a2c93661-5a16-2213-89c8-e55ff7056e36.webp', 'アプリチーム頑張ります 💪'),
            ('asuka', '007200fc-8cdf-ec09-6184-3ec9c16014c5.webp', 'I □ Flutter'),
            ('Kurogoma4D', '6badf028-a66c-ae43-338b-b162124e6f50.webp', 'アプリつくります'),
            ('いせりゅー', 'd5dcb0ae-2138-486d-801d-706e36a45ffb.webp', '個人開発で「FoodGram」のアプリを作っています！'),
            ('katsuumy', '070f9970-08dd-27d4-d80e-14c2c3236436.webp', ''),
            ('okaryo', 'e86770b3-189b-47fb-55b5-7fc4aeb560d8.webp', '💪☺️👍'),
            ('K9i', '83b2b2c4-4c28-012f-ceff-c5228859bbd5.webp', '🐙'),
            ('minn', 'cf3a6106-9815-6e08-5f32-7a1fba74c05c.webp', ''),
            ('Shohei Ogawa', '9a436d27-2d84-7d40-70cf-9bd4dcd557ef.webp', 'ヒトと技術とお酒が好き'),
            ('masa-futa', '1a0b5098-0e01-ba22-3a92-a0792b8fb260.webp', 'wai wai ٩( ''ω'' )و'),
            ('ゆう', 'e0fbf05e-371e-ad98-c50f-8b26c0752690.webp', 'よろしくお願いいたします！'),
            ('Tommy (Thomas Aquinas)', '1e58401f-d515-1ba9-c077-a0f74a3f664f.webp', ''),
            ('おはぎ(あきばこ)', '23ca6839-077e-6951-a7f3-116efc39442c.webp', ''),
            ('yasuda makoto', 'aeef0ebd-47e0-41da-9a20-17e5a5609d16.webp', ''),
            ('offich', '8a8d902b-4e5d-41fe-e745-c43e9ef9e408.webp', 'よろしくお願いいたします！'),
            ('sw', '8570633d-7a57-fc3d-5d17-a573aa241bf1.webp', ''),
            ('のり', '1ea6d5c4-29bd-393b-85fa-f977273eb0d4.webp', 'よろしくお願いします🏃'),
            ('Itsuking', 'e56ec3d2-17ac-7603-d08a-f12601dcc5aa.webp', 'Flutterエンジニア目指して転職活動中デス！よろしくお願いします！'),
            ('とまと', 'ea20b613-7e7b-461d-b508-ef705349b131.webp', 'Flutter会議盛り上げれるように頑張ります！'),
            ('Seiji', '80363ab9-42a3-859c-fd3c-a51eca85d32a.webp', 'わいわい楽しみましょー！'),
            ('Keito', '0882d1e8-33de-4eb0-9812-0d2274759ac4.webp', '個人開発が好きです！'),
            ('よう', 'a061da27-0670-a4aa-03c5-5217961d62dc.webp', '盛り上げたい！'),
            ('菊池紘', '45a33db6-15ef-ce51-2f84-60a7a0fb0286.webp', '楽しいFlutterKaigiにしよう！'),
            ('Masahiro Aoki', '3062F094-5885-4977-A992-F0EE7F03E324.jpg', 'やっぱりFlutterだなぁ。'),
            ('robo (Rie Kanetaka)', '68ec1064-9df3-4a1e-b223-87211229d026.png', 'モバイル端末好きのエンジニア'),
            ('馬渡慎之助', '485a62c6-11bf-43c1-92e6-c0e121729ddd.webp', 'ウオー🔥'),
            ('Oshiro H.', '0254e48d-cf57-47ab-9657-0856a5761926.webp', 'Flutter頑張ります！'),
            ('shanonim', '586bbd2b-b949-4ac4-b6bf-8638018d6d0e.webp', '')
    ) AS staff_members (name, icon_name, greeting)
    CROSS JOIN timestamp;

-- FlutterKaigiスタッフメンバーのSNSリンクのシードデータ
WITH
    timestamp AS (
        SELECT
            '2025-06-01 00:00:00'::timestamp AS ts
    ),
    staff_member_ids AS (
        SELECT
            name,
            id
        FROM
            public.staff_members
    )
INSERT INTO
    public.staff_member_sns_links (staff_member_id, sns_type, value, created_at, updated_at)
SELECT
    smi.id,
    sns_type::public.sns_type,
    value,
    ts,
    ts
FROM
    (
        VALUES
            ('kuno', 'github', 'kno3a87'),
            ('kuno', 'x', 'Kunodayo_oboete'),
            ('kuno', 'zenn', 'kuno'),
            ('CardsEditor', 'github', 'cardseditor'),
            ('CardsEditor', 'x', 'cardseditor'),
            ('ENDO Takumi', 'github', 'ENDOTAKUMI'),
            ('ENDO Takumi', 'x', 'endotakumi_dev'),
            ('ENDO Takumi', 'medium', 'endo.takumi.info'),
            ('ENDO Takumi', 'qiita', 'ENDOTAKUMI'),
            ('ENDO Takumi', 'zenn', 'endotakumi'),
            ('ENDO Takumi', 'note', 'endo_takumi'),
            ('ENDO Takumi', 'other', 'https://endotakumi.github.io/'),
            ('白崎 紀充', 'github', 'magnet-0113-eng'),
            ('白崎 紀充', 'x', 'magnet_0113_eng'),
            ('m.kosuke', 'github', 'shcahill'),
            ('m.kosuke', 'x', 'kosuke_mtm'),
            ('m.kosuke', 'qiita', 'mkosuke'),
            ('m.kosuke', 'zenn', 'mkosuke'),
            ('m.kosuke', 'note', 'shcahill'),
            ('Sohichiro/そーちゃん', 'github', 'sohichiro'),
            ('Sohichiro/そーちゃん', 'x', 'sohichiro'),
            ('Sohichiro/そーちゃん', 'medium', 'sohichiro'),
            ('Sohichiro/そーちゃん', 'qiita', 'sohichiro'),
            ('Sohichiro/そーちゃん', 'zenn', 'sohichiro'),
            ('Sohichiro/そーちゃん', 'note', 'sohichiro'),
            ('おかやまん', 'github', 'blendthink'),
            ('おかやまん', 'x', 'blendthink'),
            ('おかやまん', 'medium', 'blendthink'),
            ('おかやまん', 'qiita', 'blendthink'),
            ('おかやまん', 'zenn', 'blendthink'),
            ('おかやまん', 'note', 'blendthink'),
            ('ちっぴー', 'github', 'chippy-ao'),
            ('ちっぴー', 'x', 'chippy_ao'),
            ('ちっぴー', 'medium', 'chippy-ao'),
            ('ちっぴー', 'zenn', 'chippy'),
            ('もぐもぐ', 'github', 'YumNumm'),
            ('もぐもぐ', 'x', 'YumNumm'),
            ('もぐもぐ', 'medium', 'YumNumm'),
            ('もぐもぐ', 'qiita', 'YumNumm'),
            ('もぐもぐ', 'zenn', 'YumNumm'),
            ('もぐもぐ', 'other', 'https://yumnumm.dev'),
            ('jiyuujin', 'github', 'jiyuujin'),
            ('jiyuujin', 'x', 'jiyuujinlab'),
            ('jiyuujin', 'medium', 'jiyuujin'),
            ('jiyuujin', 'qiita', 'jiyuujin'),
            ('jiyuujin', 'zenn', 'jiyuujin'),
            ('jiyuujin', 'note', 'uraneko'),
            ('jiyuujin', 'other', 'https://yuma-kitamura.nekohack.me/'),
            ('うめちゃん', 'github', 'umechanhika'),
            ('うめちゃん', 'x', 'umechanhika'),
            ('うめちゃん', 'medium', 'umechanhika'),
            ('うめちゃん', 'qiita', 'umechanhika'),
            ('うめちゃん', 'zenn', 'umechanhika'),
            ('うめちゃん', 'note', 'umechanhika'),
            ('うめちゃん', 'other', 'https://umechanhika.notion.site/903ff47c623343c695ba9d4f5292e9b5'),
            ('たっつー', 'github', 'tatsutakein'),
            ('たっつー', 'x', 'tatsutakein'),
            ('たっつー', 'medium', 'tatsutakein'),
            ('たっつー', 'qiita', 'tatsutakein'),
            ('たっつー', 'zenn', 'tatsutakein'),
            ('たっつー', 'note', 'tatsutakein'),
            ('たっつー', 'other', 'https://tatsutakein.jp/'),
            ('asuka', 'github', 'a-skua'),
            ('asuka', 'x', 'a_skua'),
            ('Kurogoma4D', 'github', 'Kurogoma4D'),
            ('Kurogoma4D', 'x', 'Krgm4D'),
            ('Kurogoma4D', 'zenn', 'kurogoma4d'),
            ('Kurogoma4D', 'other', 'https://krgm4d.dev'),
            ('いせりゅー', 'github', 'iseruuuuu'),
            ('いせりゅー', 'x', 'isekiryu'),
            ('いせりゅー', 'medium', 'iseryuuuuu3'),
            ('いせりゅー', 'qiita', 'isekiryu'),
            ('いせりゅー', 'zenn', 'iseki'),
            ('いせりゅー', 'note', 'iseryu'),
            ('katsuumy', 'github', 'granoeste'),
            ('katsuumy', 'x', 'katsuumy'),
            ('okaryo', 'github', 'okaryo'),
            ('okaryo', 'x', 'okaryoX'),
            ('okaryo', 'medium', 'okaryo'),
            ('K9i', 'github', 'K9i-0'),
            ('K9i', 'x', 'K9i_apps'),
            ('K9i', 'medium', 'K9i'),
            ('K9i', 'qiita', 'K9i-0'),
            ('K9i', 'zenn', 'k9i'),
            ('minn', 'github', 'kitashio'),
            ('minn', 'x', 'minn_flutter'),
            ('minn', 'zenn', 'minn'),
            ('Shohei Ogawa', 'github', 'heyhey1028'),
            ('Shohei Ogawa', 'x', 'heyhey1028'),
            ('Shohei Ogawa', 'qiita', 'heyhey1028'),
            ('Shohei Ogawa', 'zenn', 'heyhey1028'),
            ('masa-futa', 'github', 'masa-futa'),
            ('masa-futa', 'x', 'ma12441469'),
            ('masa-futa', 'medium', 'masakunn1215'),
            ('masa-futa', 'qiita', 'masakunn1215'),
            ('masa-futa', 'zenn', 'masakunn'),
            ('ゆう', 'github', 'yu-s1127'),
            ('ゆう', 'x', 'yu_s1127'),
            ('Tommy (Thomas Aquinas)', 'x', 'ThomasS2558'),
            ('おはぎ(あきばこ)', 'github', 'akeybako'),
            ('おはぎ(あきばこ)', 'x', 'a_key_bako'),
            ('yasuda makoto', 'x', '1234567890kuro'),
            ('offich', 'github', 'offich'),
            ('offich', 'x', 'offichy'),
            ('offich', 'other', 'https://offich.me'),
            ('sw', 'x', 's4y_wt'),
            ('のり', 'x', 'no_main_'),
            ('Itsuking', 'github', 'Ituking'),
            ('Itsuking', 'x', 'IamItsuking'),
            ('とまと', 'github', 'tomoki1590'),
            ('とまと', 'x', '1234568aasobso1'),
            ('とまと', 'qiita', 'kagura1'),
            ('とまと', 'zenn', 'tomato1'),
            ('Seiji', 'github', 'n-seiji'),
            ('Seiji', 'x', 'se_eiji'),
            ('Seiji', 'qiita', 'se_eiji'),
            ('Seiji', 'zenn', 'seeiji'),
            ('Seiji', 'other', 'https://www.sijis.me/'),
            ('Keito', 'github', 'keitokusano'),
            ('Keito', 'x', 'techkeito'),
            ('Keito', 'medium', 'techkeito'),
            ('Keito', 'qiita', 'kusano_keito'),
            ('Keito', 'zenn', 'keito'),
            ('よう', 'github', 'KobayashiYoh'),
            ('よう', 'x', 'yoyoh_'),
            ('よう', 'qiita', 'yoyoh_'),
            ('よう', 'zenn', 'yoyoh'),
            ('菊池紘', 'github', 'kikuchy'),
            ('菊池紘', 'x', 'kikuchy'),
            ('菊池紘', 'qiita', 'kikuchy'),
            ('菊池紘', 'zenn', 'kikuchy'),
            ('Masahiro Aoki', 'x', 'ma_freud'),
            ('robo (Rie Kanetaka)', 'x', 'cch_robo'),
            ('馬渡慎之助', 'x', 'hensyunoouma'),
            ('Oshiro H.', 'github', 'HiroshiOshiro'),
            ('shanonim', 'x', 'shanonim')
    ) AS sns_data (staff_name, sns_type, value)
    JOIN staff_member_ids smi ON smi.name = sns_data.staff_name
    CROSS JOIN timestamp;
