name: bff_client
publish_to: none

resolution: workspace

environment:
  sdk: ^3.10.0-75.1.beta

dependencies:
  db_types:
    path: ../db_types
  dio: ^5.8.0+1
  freezed_annotation: ^3.0.0
  json_annotation: ^4.9.0
  retrofit: ^4.4.2

dev_dependencies:
  altive_lints: ^1.19.1
  build_runner: ^2.4.15
  custom_lint: ^0.8.0
  flutterkaigi_lints:
    path: ../flutterkaigi_lints
  freezed: ^3.0.6
  json_serializable: ^6.9.5
  retrofit_generator: ^10.0.0
  test: ^1.25.15
