import 'dart:convert';
import 'dart:io';

import 'package:bff_client/bff_client.dart';
import 'package:dio/dio.dart';

/// ビルド時にBFF APIからセッション情報を取得して、
/// JSONファイルとして生成するスクリプト
Future<void> main() async {
  // 環境変数からBFF_BASE_URLを取得、なければデフォルト値（prod）を使用
  const defaultBffBaseUrl = 'https://2025-bff.flutterkaigi.jp/v1';
  final bffBaseUrl = Platform.environment['BFF_BASE_URL'] ?? defaultBffBaseUrl;

  if (bffBaseUrl.isEmpty) {
    stderr.writeln('Error: BFF_BASE_URL is empty');
    exit(1);
  }

  print('Fetching session data from: $bffBaseUrl');

  // BFFクライアントの初期化（認証なし）
  final dio = Dio(BaseOptions(baseUrl: bffBaseUrl));
  final apiClient = BffApiClient(dio: dio);

  try {
    // タイムラインイベントを取得
    final timelineResponse = await apiClient.v1.session.getTimelineEvents();
    final events = timelineResponse.data.events;

    // セッションスケジュールを取得
    final scheduleResponse = await apiClient.v1.session.getSessionSchedule();
    final schedule = scheduleResponse.data.schedule;

    // 会場別セッションを取得
    final venuesResponse = await apiClient.v1.session.getSessionsByVenue();
    final venues = venuesResponse.data.venues;

    print('Fetched ${events.length} timeline events');
    print('Fetched ${schedule.length} schedule entries');
    print('Fetched ${venues.length} venues');

    // JSONファイルとして生成
    final jsonData = {
      'timelineEvents': events.map((e) => e.toJson()).toList(),
      'sessionSchedule': schedule.map(
        (key, value) => MapEntry(
          key,
          value.map((s) => s.toJson()).toList(),
        ),
      ),
      'venuesWithSessions': venues.map((v) => v.toJson()).toList(),
    };

    final jsonOutput = const JsonEncoder.withIndent('  ').convert(jsonData);

    // JSONファイルに書き込み
    final jsonFile = File('lib/src/config/sessions_data.json');
    await jsonFile.writeAsString(jsonOutput);
    print('Generated: ${jsonFile.path}');

    // Dartファイルとして JSON文字列を定義
    final dartContent = '''
// GENERATED FILE - DO NOT EDIT
// This file is generated by tool/fetch_sessions.dart

/// セッションデータのJSON文字列
const String sessionsDataJson = r\'\'\'
$jsonOutput
\'\'\';
''';

    final dartFile = File('lib/src/config/sessions_data.json.dart');
    await dartFile.writeAsString(dartContent);
    print('Generated: ${dartFile.path}');

    print('Done!');
  } catch (e, stackTrace) {
    stderr.writeln('Error fetching session data: $e');
    stderr.writeln(stackTrace);
    exit(1);
  }
}
