import 'dart:convert';
import 'dart:io';

import 'package:bff_client/bff_client.dart';
import 'package:dio/dio.dart';

/// ビルド時にBFF APIからセッション情報を取得して、
/// Dartファイルとして生成するスクリプト
Future<void> main() async {
  // 環境変数からBFF_BASE_URLを取得、なければデフォルト値（prod）を使用
  const defaultBffBaseUrl = 'https://2025-bff.flutterkaigi.jp/v1';
  final bffBaseUrl = Platform.environment['BFF_BASE_URL'] ?? defaultBffBaseUrl;

  if (bffBaseUrl.isEmpty) {
    stderr.writeln('Error: BFF_BASE_URL is empty');
    exit(1);
  }

  print('Fetching session data from: $bffBaseUrl');

  // BFFクライアントの初期化（認証なし）
  final dio = Dio(BaseOptions(baseUrl: bffBaseUrl));
  final apiClient = BffApiClient(dio: dio);

  try {
    // タイムラインイベントを取得
    final timelineResponse = await apiClient.v1.session.getTimelineEvents();
    final events = timelineResponse.data.events;

    // セッションスケジュールを取得
    final scheduleResponse = await apiClient.v1.session.getSessionSchedule();
    final schedule = scheduleResponse.data.schedule;

    // 会場別セッションを取得
    final venuesResponse = await apiClient.v1.session.getSessionsByVenue();
    final venues = venuesResponse.data.venues;

    print('Fetched ${events.length} timeline events');
    print('Fetched ${schedule.length} schedule entries');
    print('Fetched ${venues.length} venues');

    // Dartファイルとして生成
    final output = _generateDartFile(events, schedule, venues);

    // ファイルに書き込み
    final file = File('lib/src/config/sessions_data.g.dart');
    await file.writeAsString(output);

    print('Generated: ${file.path}');
    print('Done!');
  } catch (e, stackTrace) {
    stderr.writeln('Error fetching session data: $e');
    stderr.writeln(stackTrace);
    exit(1);
  }
}

String _generateDartFile(
  List<TimelineEvent> events,
  Map<String, List<ScheduleSession>> schedule,
  List<VenueWithSessions> venues,
) {
  final buffer = StringBuffer();

  // ファイルヘッダー
  buffer.writeln('// GENERATED CODE - DO NOT MODIFY BY HAND');
  buffer.writeln('// Generated by tool/fetch_sessions.dart');
  buffer.writeln('// ignore_for_file: lines_longer_than_80_chars');
  buffer.writeln();
  buffer.writeln("import 'package:bff_client/bff_client.dart';");
  buffer.writeln();

  // タイムラインイベントのリスト
  buffer.writeln('/// BFF APIから取得したタイムラインイベント');
  buffer.writeln('final timelineEvents = <TimelineEvent>[');
  for (final event in events) {
    buffer.writeln('  TimelineEvent(');
    buffer.writeln("    id: '${_escapeString(event.id)}',");
    buffer.writeln("    title: '${_escapeString(event.title)}',");
    buffer.writeln(
      "    startsAt: DateTime.parse('${event.startsAt.toUtc().toIso8601String()}'),",
    );
    if (event.endsAt != null) {
      buffer.writeln(
        "    endsAt: DateTime.parse('${event.endsAt!.toUtc().toIso8601String()}'),",
      );
    } else {
      buffer.writeln('    endsAt: null,');
    }
    if (event.venue != null) {
      buffer.writeln('    venue: Venue(');
      buffer.writeln("      id: '${_escapeString(event.venue!.id)}',");
      buffer.writeln("      name: '${_escapeString(event.venue!.name)}',");
      buffer.writeln('    ),');
    } else {
      buffer.writeln('    venue: null,');
    }
    buffer.writeln('  ),');
  }
  buffer.writeln('];');
  buffer.writeln();

  // スケジュールマップ
  buffer.writeln('/// BFF APIから取得したセッションスケジュール');
  buffer.writeln('final sessionSchedule = <String, List<ScheduleSession>>{');
  schedule.forEach((venueId, sessions) {
    buffer.writeln("  '${_escapeString(venueId)}': [");
    for (final session in sessions) {
      buffer.writeln('    ScheduleSession(');
      buffer.writeln("      venue: '${_escapeString(session.venue)}',");
      buffer.writeln("      venueId: '${_escapeString(session.venueId)}',");
      buffer.writeln("      id: '${_escapeString(session.id)}',");
      buffer.writeln("      title: '${_escapeString(session.title)}',");
      buffer.writeln(
        "      description: '${_escapeString(session.description)}',",
      );
      buffer.writeln(
        "      startsAt: DateTime.parse('${session.startsAt.toUtc().toIso8601String()}'),",
      );
      buffer.writeln(
        "      endsAt: DateTime.parse('${session.endsAt.toUtc().toIso8601String()}'),",
      );
      buffer.writeln(
        '      isLightningTalk: ${session.isLightningTalk},',
      );
      buffer.writeln(
        '      isBeginnersLightningTalk: ${session.isBeginnersLightningTalk},',
      );
      buffer.writeln('      isHandsOn: ${session.isHandsOn},');
      buffer.writeln('      speakers: [');
      for (final speaker in session.speakers) {
        buffer.writeln('        Speaker(');
        buffer.writeln("          id: '${_escapeString(speaker.id)}',");
        buffer.writeln("          name: '${_escapeString(speaker.name)}',");
        buffer.writeln(
          "          avatarUrl: ${speaker.avatarUrl != null ? "'${_escapeString(speaker.avatarUrl!)}'" : 'null'},",
        );
        buffer.writeln(
          "          xId: ${speaker.xId != null ? "'${_escapeString(speaker.xId!)}'" : 'null'},",
        );
        buffer.writeln('        ),');
      }
      buffer.writeln('      ],');
      buffer.writeln(
        "      videoUrl: ${session.videoUrl != null ? "'${_escapeString(session.videoUrl!)}'" : 'null'},",
      );
      buffer.writeln(
        "      url: ${session.url != null ? "'${_escapeString(session.url!)}'" : 'null'},",
      );
      if (session.sponsor != null) {
        final sponsor = session.sponsor!;
        buffer.writeln('      sponsor: Sponsor(');
        buffer.writeln('        id: ${sponsor.id},');
        buffer.writeln("        name: '${_escapeString(sponsor.name)}',");
        buffer.writeln("        logoUrl: '${_escapeString(sponsor.logoUrl)}',");
        buffer.writeln("        slug: '${_escapeString(sponsor.slug)}',");
        buffer.writeln("        prText: '${_escapeString(sponsor.prText)}',");
        buffer.writeln(
          "        websiteUrl: '${_escapeString(sponsor.websiteUrl)}',",
        );
        buffer.writeln(
          "        sponsorType: '${_escapeString(sponsor.sponsorType)}',",
        );
        buffer.writeln(
          "        displayOrder: '${_escapeString(sponsor.displayOrder)}',",
        );
        buffer.writeln(
          "        optionPlanTypes: ${jsonEncode(sponsor.optionPlanTypes)},",
        );
        buffer.writeln(
          "        basicPlanType: ${sponsor.basicPlanType != null ? "'${_escapeString(sponsor.basicPlanType!)}'" : 'null'},",
        );
        buffer.writeln('      ),');
      } else {
        buffer.writeln('      sponsor: null,');
      }
      buffer.writeln('    ),');
    }
    buffer.writeln('  ],');
  });
  buffer.writeln('};');
  buffer.writeln();

  // 会場別セッション
  buffer.writeln('/// BFF APIから取得した会場別セッション');
  buffer.writeln('final venuesWithSessions = <VenueWithSessions>[');
  for (final venue in venues) {
    buffer.writeln('  VenueWithSessions(');
    buffer.writeln("    id: '${_escapeString(venue.id)}',");
    buffer.writeln("    name: '${_escapeString(venue.name)}',");
    buffer.writeln('    sessions: [');
    for (final session in venue.sessions) {
      buffer.writeln('      SessionWithSpeakers(');
      buffer.writeln("        id: '${_escapeString(session.id)}',");
      buffer.writeln("        title: '${_escapeString(session.title)}',");
      buffer.writeln(
        "        description: '${_escapeString(session.description)}',",
      );
      buffer.writeln(
        "        startsAt: DateTime.parse('${session.startsAt.toUtc().toIso8601String()}'),",
      );
      buffer.writeln(
        "        endsAt: DateTime.parse('${session.endsAt.toUtc().toIso8601String()}'),",
      );
      buffer.writeln(
        '        isLightningTalk: ${session.isLightningTalk},',
      );
      buffer.writeln(
        '        isBeginnersLightningTalk: ${session.isBeginnersLightningTalk},',
      );
      buffer.writeln('        isHandsOn: ${session.isHandsOn},');
      buffer.writeln('        speakers: [');
      for (final speaker in session.speakers) {
        buffer.writeln('          Speaker(');
        buffer.writeln("            id: '${_escapeString(speaker.id)}',");
        buffer.writeln("            name: '${_escapeString(speaker.name)}',");
        buffer.writeln(
          "            avatarUrl: ${speaker.avatarUrl != null ? "'${_escapeString(speaker.avatarUrl!)}'" : 'null'},",
        );
        buffer.writeln(
          "            xId: ${speaker.xId != null ? "'${_escapeString(speaker.xId!)}'" : 'null'},",
        );
        buffer.writeln('          ),');
      }
      buffer.writeln('        ],');
      buffer.writeln(
        "        videoUrl: ${session.videoUrl != null ? "'${_escapeString(session.videoUrl!)}'" : 'null'},",
      );
      buffer.writeln(
        "        url: ${session.url != null ? "'${_escapeString(session.url!)}'" : 'null'},",
      );
      if (session.sponsor != null) {
        final sponsor = session.sponsor!;
        buffer.writeln('        sponsor: Sponsor(');
        buffer.writeln('          id: ${sponsor.id},');
        buffer.writeln("          name: '${_escapeString(sponsor.name)}',");
        buffer.writeln(
          "          logoUrl: '${_escapeString(sponsor.logoUrl)}',",
        );
        buffer.writeln("          slug: '${_escapeString(sponsor.slug)}',");
        buffer.writeln("          prText: '${_escapeString(sponsor.prText)}',");
        buffer.writeln(
          "          websiteUrl: '${_escapeString(sponsor.websiteUrl)}',",
        );
        buffer.writeln(
          "          sponsorType: '${_escapeString(sponsor.sponsorType)}',",
        );
        buffer.writeln(
          "          displayOrder: '${_escapeString(sponsor.displayOrder)}',",
        );
        buffer.writeln(
          "          optionPlanTypes: ${jsonEncode(sponsor.optionPlanTypes)},",
        );
        buffer.writeln(
          "          basicPlanType: ${sponsor.basicPlanType != null ? "'${_escapeString(sponsor.basicPlanType!)}'" : 'null'},",
        );
        buffer.writeln('        ),');
      } else {
        buffer.writeln('        sponsor: null,');
      }
      buffer.writeln('      ),');
    }
    buffer.writeln('    ],');
    buffer.writeln('  ),');
  }
  buffer.writeln('];');

  return buffer.toString();
}

String _escapeString(String str) {
  return str
      .replaceAll('\\', '\\\\')
      .replaceAll("'", "\\'")
      .replaceAll('\n', '\\n')
      .replaceAll('\r', '\\r')
      .replaceAll('\t', '\\t');
}
