import 'dart:convert';
import 'dart:io';

import 'package:bff_client/bff_client.dart';
import 'package:dio/dio.dart';

/// ビルド時にBFF APIからスポンサー情報を取得して、
/// JSONファイルとして生成するスクリプト
Future<void> main() async {
  // 環境変数からBFF_BASE_URLを取得、なければデフォルト値（prod）を使用
  const defaultBffBaseUrl = 'https://2025-bff.flutterkaigi.jp/v1';
  final bffBaseUrl = Platform.environment['BFF_BASE_URL'] ?? defaultBffBaseUrl;

  if (bffBaseUrl.isEmpty) {
    stderr.writeln('Error: BFF_BASE_URL is empty');
    exit(1);
  }

  print('Fetching sponsor data from: $bffBaseUrl');

  // BFFクライアントの初期化(認証なし)
  final dio = Dio(BaseOptions(baseUrl: bffBaseUrl));
  final apiClient = BffApiClient(dio: dio);

  try {
    // スポンサー情報のサマリーを取得
    final sponsorSummary = await apiClient.v1.sponsors.getSponsors();

    print(
      'Fetched ${sponsorSummary.companySponsors.length} company sponsors',
    );
    print(
      'Fetched ${sponsorSummary.individualSponsors.length} individual sponsors',
    );

    // JSONファイルとして生成
    final jsonData = sponsorSummary.toJson();

    final jsonOutput = const JsonEncoder.withIndent('  ').convert(jsonData);

    // JSONファイルに書き込み
    final jsonFile = File('lib/src/config/sponsors_data.json');
    await jsonFile.writeAsString(jsonOutput);
    print('Generated: ${jsonFile.path}');

    // Dartファイルとして JSON文字列を定義
    final dartContent = '''
// GENERATED FILE - DO NOT EDIT
// This file is generated by tool/fetch_sponsors.dart

/// スポンサーデータのJSON文字列
const String sponsorsDataJson = r\'\'\'
$jsonOutput
\'\'\';
''';

    final dartFile = File('lib/src/config/sponsors_data.json.dart');
    await dartFile.writeAsString(dartContent);
    print('Generated: ${dartFile.path}');

    print('Done!');
  } catch (e, stackTrace) {
    stderr.writeln('Error fetching sponsor data: $e');
    stderr.writeln(stackTrace);
    exit(1);
  }
}
