[env]
'_'.source = "scripts/export_sops_key_path.sh"
'_'.file.path = ".env.json"

SUPABASE_ACCESS_TOKEN = "{{ env.TF_VAR_SUPABASE_ACCESS_TOKEN }}"

[settings.sops]
age_key_file = "~/.config/mise/flutterkaigi.txt"
