[tools]
"aqua:suzuki-shunsuke/tfcmt" = "4.14.5"
bun = "1.2.10"
deno = "2.2.12"
flutter = "3.29.3-stable"
node = "22.14.0"
terraform = "1.11.4"
tflint = "0.56.0"

[tasks.bootstrap]
description = "Initialize the workspace."
run = './tools/bootstrap.sh'
alias = "bs"
