[tools]
"aqua:suzuki-shunsuke/tfcmt" = "latest"
aws-cli = "latest"
bun = "1.2.21"
dprint = "latest"
flutter = "3.38.0-0.1.pre-beta"
node = "24.4.0"
"pipx:codemagic-cli-tools" = "0.61.1"
rclone = "latest"
stripe = "latest"
swift = "latest"
terraform = "latest"
tflint = "latest"
uv = "latest"
websocat = "latest"

[env]
'_'.source = "scripts/export_sops_key_path.sh"
'_'.file.path = ".env.json"

SUPABASE_ACCESS_TOKEN = "{{ env.TF_VAR_SUPABASE_ACCESS_TOKEN }}"

[settings.sops]
age_key_file = "~/.config/mise/flutterkaigi.txt"

[tasks.bootstrap]
description = "Initialize the workspace."
run = './scripts/bootstrap.sh'
alias = "bs"

[tasks.clean]
description = "Clean this workspace."
run = [
  'bun run clean',
  'melos clean',
]

[settings]
lockfile = true
experimental = true
