[tools]
"aqua:suzuki-shunsuke/tfcmt" = "latest"
aws-cli = "latest"
bun = "1.2.21"
dprint = "latest"
flutter = "3.36.0-0.1.pre-beta"
node = "24.4.0"
rclone = "latest"
stripe = "latest"
terraform = "latest"
tflint = "latest"

[env.'_']
file.path = "bff/engine/.env"

[tasks.bootstrap]
description = "Initialize the workspace."
run = './tools/bootstrap.sh'
alias = "bs"

[tasks.clean]
description = "Clean this workspace."
run = [
  'bun run clean',
  'melos clean',
]

[settings]
lockfile = true
experimental = true
