[tools]
"aqua:suzuki-shunsuke/tfcmt" = "4.14.7"
bun = "1.2.21"
dprint = "0.50.1"
flutter = "3.36.0-0.1.pre-beta"
node = "24.4.0"
rclone = "1.70.3"
stripe = "latest"
terraform = "1.12.2"
tflint = "0.58.0"

[env.'_']
file.path = "bff/engine/.env"

[tasks.bootstrap]
description = "Initialize the workspace."
run = './tools/bootstrap.sh'
alias = "bs"

[tasks.clean]
description = "Clean this workspace."
run = [
  'bun run clean',
  'melos clean',
]
