name: flutterkaigi_2025
publish_to: none

environment:
  sdk: ^3.10.0-209.1.beta
  flutter: ^3.38.0-0.1.pre

dependency_overrides:
  dartastic_opentelemetry:
    git:
      url: https://github.com/YumNumm/dartastic_opentelemetry.git
      ref: c74d9ff9b90546d071537ead242a79b7286949be
  protobuf: ^4.2.0

dev_dependencies:
  melos: ^7.2.0

workspace:
  # apps
  - apps/app
  - apps/app_catalog
  - apps/website
  # packages
  - packages/flutterkaigi_lints
  - packages/bff_client
  - packages/db_types
  - packages/auth_client
  - packages/db_client
  - packages/internal_api_client
  - packages/_base
  # bff
  - bff/engine

melos:
  ide:
    intellij:
      enabled: false

  command:
    bootstrap:
      environment:
        sdk: ^3.10.0-209.1.beta
        flutter: ^3.38.0-0.1.pre
      dependencies:
        flutter_localizations:
          sdk: flutter
        go_router: ^16.2.1
        intl: ^0.20.2
        url_launcher: ^6.3.1
      dev_dependencies:
        altive_lints: ^1.19.1
        build_runner: ^2.4.15
        go_router_builder: ^4.1.0
        test: ^1.25.15

  scripts:
    gen:
      description: build_runner と i18n の生成コマンドを実行します。
      steps:
        - gen:i18n
        - gen:build
    gen:build:
      description: build_runner を使用してコードを生成します。
      run: dart run build_runner build -d
      exec:
        orderDependents: true
      packageFilters:
        dependsOn: build_runner
    gen:build:watch:
      description: build_runner watch を使用して、変更箇所を検知しつつコードを生成します。
      run: dart run build_runner watch -d
      exec:
        orderDependents: true
      packageFilters:
        dependsOn: build_runner
    gen:i18n:
      description: slang を使用して国際化ファイルを生成します。
      run: dart run slang
      exec:
        orderDependents: true
      packageFilters:
        dependsOn: slang

    gen:diff:head:
      description: 未コミットの差分パッケージのみ build_runner と i18n の生成コマンドを実行します。
      steps:
        - gen:build:diff:head
        - gen:i18n:diff:head
    gen:build:diff:head:
      description: 未コミットの差分パッケージのみ build_runner を使用してコードを生成します。
      run: dart run build_runner build -d
      exec:
        orderDependents: true
      packageFilters:
        dependsOn: build_runner
        diff: "" # --diff=HEAD のワークアラウンド https://github.com/invertase/melos/issues/759
    gen:i18n:diff:head:
      description: 未コミットの差分パッケージのみ slang を使用して国際化ファイルを生成します。
      run: dart run slang
      exec:
        orderDependents: true
      packageFilters:
        dependsOn: slang
        diff: "" # --diff=HEAD のワークアラウンド https://github.com/invertase/melos/issues/759

    gen:diff:main:
      description: main ブランチと差分のあるパッケージのみ build_runner と i18n の生成コマンドを実行します。
      steps:
        - gen:build:diff:main
        - gen:i18n:diff:main
    gen:build:diff:main:
      description: main ブランチと差分のあるパッケージのみ build_runner を使用してコードを生成します。
      run: dart run build_runner build -d
      exec:
        orderDependents: true
      packageFilters:
        dependsOn: build_runner
        diff: origin/main...HEAD
    gen:i18n:diff:main:
      description: main ブランチと差分のあるパッケージのみ slang を使用して国際化ファイルを生成します。
      run: dart run slang
      exec:
        orderDependents: true
      packageFilters:
        dependsOn: slang
        diff: origin/main...HEAD

    fix:
      exec: dart fix --apply lib
      description: Run dart fix.
      packageFilters:
        dirExists: lib
    fix:check:
      exec: dart fix --dry-run lib
      description: Check dart fix.
      packageFilters:
        dirExists: lib
    fix:custom:
      description: すべてのパッケージに custom_lint の fix を実行します。
      exec: dart run custom_lint --fix
      packageFilters:
        dirExists: lib
        dependsOn: custom_lint
    format:
      exec: >-
        find lib -name "*.dart"
        -not -path "*/\.*"
        -not -path "*/build/*"
        -not -path "*/generated/*"
        -not -name "*.g.dart"
        -not -name "*.freezed.dart"
        -not -name "*.gen.dart" | xargs dart format
      description: Run format.
      packageFilters:
        dirExists: lib
    format:check:
      exec: >-
        find lib -name "*.dart"
        -not -path "*/\.*"
        -not -path "*/build/*"
        -not -path "*/generated/*"
        -not -name "*.g.dart"
        -not -name "*.freezed.dart"
        -not -name "*.gen.dart" | xargs dart format --output=none --set-exit-if-changed
      description: Check format.
      packageFilters:
        dirExists: lib

    test:
      description: すべてのパッケージのテストを実行します。
      steps:
        - test:dart
        - test:flutter
    test:dart:
      description: Dart パッケージのテストを実行します。
      run: dart test
      exec:
        concurrency: 1
      packageFilters:
        dependsOn: test
        dirExists: test
      env:
        MELOS_TEST: true
    test:flutter:
      description: Flutter パッケージのテストを実行します。
      run: flutter test
      exec:
        concurrency: 1
      packageFilters:
        dependsOn: flutter_test
        dirExists: test
      env:
        MELOS_TEST: true
