services:
  fcm-internal-api:
    build:
      context: ../../
      dockerfile: bff/fcm-internal-api/Dockerfile
      platforms:
        - linux/amd64
    platform: linux/amd64
    ports:
      - "8080:8080"
    env_file:
      - .env
