name: db_client
publish_to: none

resolution: workspace

environment:
  sdk: ^3.10.0-209.1.beta

dependencies:
  db_types:
    path: ../db_types
  freezed_annotation: ^3.0.0
  json_annotation: ^4.9.0
  postgres: ^3.5.6

dev_dependencies:
  altive_lints: ^1.19.1
  build_runner: ^2.4.15
  custom_lint: ^0.8.0
  flutterkaigi_lints:
    path: ../flutterkaigi_lints
  freezed: ^3.0.6
  json_serializable: ^6.9.5
  test: ^1.25.15
