// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCs-GJGkRZngnRUpFHXM1uRjZWRnVt3DnE',
    appId: '1:56595340575:web:b943411f3f065e4dd8642a',
    messagingSenderId: '56595340575',
    projectId: 'flutterkaigi2025-prod-8f66',
    authDomain: 'flutterkaigi2025-prod-8f66.firebaseapp.com',
    storageBucket: 'flutterkaigi2025-prod-8f66.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBk74vR2MlODwXYkXCRP61woGfuWMpdndw',
    appId: '1:56595340575:android:c6c9c0c319b4f2f7d8642a',
    messagingSenderId: '56595340575',
    projectId: 'flutterkaigi2025-prod-8f66',
    storageBucket: 'flutterkaigi2025-prod-8f66.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8tNPfkubOGE7ART53gW0xbtn_Y5Hcfsg',
    appId: '1:56595340575:ios:f401145487e68533d8642a',
    messagingSenderId: '56595340575',
    projectId: 'flutterkaigi2025-prod-8f66',
    storageBucket: 'flutterkaigi2025-prod-8f66.firebasestorage.app',
    iosBundleId: 'jp.flutterkaigi.conf2025',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD8tNPfkubOGE7ART53gW0xbtn_Y5Hcfsg',
    appId: '1:56595340575:ios:f401145487e68533d8642a',
    messagingSenderId: '56595340575',
    projectId: 'flutterkaigi2025-prod-8f66',
    storageBucket: 'flutterkaigi2025-prod-8f66.firebasestorage.app',
    iosBundleId: 'jp.flutterkaigi.conf2025',
  );
}
