// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGLmkhELrH78AsSIqXVwDT5SncZ5e-u2Y',
    appId: '1:1024337697305:web:27d4b991dc2ed7a794a888',
    messagingSenderId: '1024337697305',
    projectId: 'flutterkaigi2025-stg-8f66',
    authDomain: 'flutterkaigi2025-stg-8f66.firebaseapp.com',
    storageBucket: 'flutterkaigi2025-stg-8f66.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKssbiiRCxIgCD2SchUbYq0MFcYgWpo3o',
    appId: '1:1024337697305:android:165ac1937f5e4ac094a888',
    messagingSenderId: '1024337697305',
    projectId: 'flutterkaigi2025-stg-8f66',
    storageBucket: 'flutterkaigi2025-stg-8f66.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJgaeEsrmVl99Y_9Nxt3G6Q9mIwX4vuiM',
    appId: '1:1024337697305:ios:2e8758ea13b297da94a888',
    messagingSenderId: '1024337697305',
    projectId: 'flutterkaigi2025-stg-8f66',
    storageBucket: 'flutterkaigi2025-stg-8f66.firebasestorage.app',
    iosBundleId: 'jp.flutterkaigi.conf2025.stg',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJgaeEsrmVl99Y_9Nxt3G6Q9mIwX4vuiM',
    appId: '1:1024337697305:ios:2e8758ea13b297da94a888',
    messagingSenderId: '1024337697305',
    projectId: 'flutterkaigi2025-stg-8f66',
    storageBucket: 'flutterkaigi2025-stg-8f66.firebasestorage.app',
    iosBundleId: 'jp.flutterkaigi.conf2025.stg',
  );
}
