services:
  bff-engine:
    build:
      context: ../../
      dockerfile: bff/engine/Dockerfile
      platforms:
        - linux/amd64
    platform: linux/amd64
    ports:
      - "8080:8080"
    env_file:
      - .env
    restart: unless-stopped
