[tools]
dart = "stable"

[tasks.build]
description = "Build the Dart Frog application"
run = [
  'dart pub get',
  'dart pub global activate dart_frog_cli',
  'dart pub global run dart_frog_cli:dart_frog build',
  'dart compile exe build/bin/server.dart -o build/bin/server'
]

[tasks.dev]
description = "Run the development server"
run = 'dart_frog dev'

[tasks.test]
description = "Run tests"
run = 'dart test'
