name: engine
version: 1.0.0
publish_to: none

resolution: workspace

environment:
  sdk: ^3.9.0-100.2.beta

dependencies:
  bff_client:
    path: ../../packages/bff_client
  db_client:
    path: ../../packages/db_client
  db_types:
    path: ../../packages/db_types
  freezed_annotation: ^3.0.0
  http: ^1.4.0
  js_interop_utils: ^1.0.7
  json_annotation: ^4.9.0
  riverpod: ^3.0.0-dev.15
  riverpod_annotation: ^3.0.0-dev.15
  shelf: ^1.4.2
  shelf_router: ^1.1.4
  supabase: ^2.7.0
  web: ^1.1.1

dev_dependencies:
  altive_lints: ^1.19.1
  build_runner: ^2.4.15
  custom_lint: ^0.7.5
  flutterkaigi_lints:
    path: ../../packages/flutterkaigi_lints
  freezed: ^3.0.6
  json_serializable: ^6.9.5
  riverpod_generator: ^3.0.0-dev.15
  riverpod_lint: ^3.0.0-dev.15
  shelf_router_generator: ^1.1.1
