name: engine
version: 1.0.0
publish_to: none

resolution: workspace

environment:
  sdk: ^3.7.2

dependencies:
  js_interop_utils: ^1.0.7
  riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  shelf: ^1.4.2
  shelf_router: ^1.1.4
  web: ^1.1.1

dev_dependencies:
  http: ^1.3.0
  build_runner: ^2.4.15
  custom_lint: ^0.7.5
  riverpod_generator: ^2.6.5
  riverpod_lint: ^2.6.5
  shelf_router_generator: ^1.1.1
