name: engine
version: 1.0.0
publish_to: none

resolution: workspace

environment:
  sdk: ^3.9.0-100.2.beta

dependencies:
  bff_client:
    path: ../../packages/bff_client
  db_client:
    path: ../../packages/db_client
  db_types:
    path: ../../packages/db_types
  dio: ^5.8.0+1
  freezed_annotation: ^3.0.0
  http: ^1.4.0
  internal_api_client:
    path: ../../packages/internal_api_client
  json_annotation: ^4.9.0
  riverpod: ^3.0.0-dev.16
  riverpod_annotation: ^3.0.0-dev.16
  shelf: ^1.4.0
  shelf_router: ^1.1.4
  supabase: ^2.7.0

dev_dependencies:
  altive_lints: ^1.19.1
  build_runner: ^2.4.15
  custom_lint: ^0.7.5
  flutterkaigi_lints:
    path: ../../packages/flutterkaigi_lints
  freezed: ^3.0.6
  json_serializable: ^6.9.5
  mocktail: ^1.0.4
  riverpod_generator: ^3.0.0-dev.16
  riverpod_lint: ^3.0.0-dev.16
  shelf_router_generator: ^1.0.0
  test: ^1.24.3
