name: engine
version: 1.0.0
publish_to: none

resolution: workspace

environment:
  sdk: ^3.8.0-278.2.beta

dependencies:
  freezed_annotation: ^3.0.0
  js_interop_utils: ^1.0.7
  json_annotation: ^4.9.0
  riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  shelf: ^1.4.2
  shelf_router: ^1.1.4
  web: ^1.1.1

dev_dependencies:
  altive_lints: ^1.19.1
  build_runner: ^2.4.15
  custom_lint: ^0.7.5
  flutterkaigi_lints:
    path: ../../packages/flutterkaigi_lints
  freezed: ^3.0.6
  http: ^1.3.0
  json_serializable: ^6.9.5
  riverpod_generator: ^2.6.5
  riverpod_lint: ^2.6.5
  shelf_router_generator: ^1.1.1
