include: package:flutterkaigi_lints/analysis_options.yaml

custom_lint:
  rules:
    - avoid_hardcoded_color: false
    - avoid_hardcoded_japanese: false
    - prefer_clock_now: false
analyzer:
  errors:
    always_put_required_named_parameters_first: ignore
