name: app_catalog
description: "FlutterKaigi 2025 Conference Application Catalog"
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.10.0-209.1.beta
  flutter: ^3.38.0-0.1.pre

resolution: workspace

dependencies:
  app: any
  auth_client: any
  bff_client: any
  cupertino_icons: 1.0.8
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  hooks_riverpod: ^3.0.3
  slang_flutter: ^4.8.0
  widgetbook: ^3.16.0
  widgetbook_annotation: ^3.7.0

dev_dependencies:
  build_runner: ^2.4.15
  custom_lint: ^0.8.0
  flutter_test:
    sdk: flutter
  flutterkaigi_lints: any
  widgetbook_generator: ^3.16.0

flutter:
  uses-material-design: true
