include: package:flutterkaigi_lints/analysis_options.yaml

analyzer:
  exclude:
    - lib/jaspr_options.dart
    - lib/src/config/sessions_data.g.dart
  plugins:
    - custom_lint

custom_lint:
  rules:
    - avoid_hardcoded_color: false
    - avoid_hardcoded_japanese: false
    - prefer_clock_now: false

linter:
  rules:
    # `elements.forEach(append)`と書いた時にWasmのビルドに失敗したため無効化
    unnecessary_lambdas: false
    # avoid_function_literals_in_foreach_calls とconflictするので無効化
    prefer_foreach: false
