"$schema" = "node_modules/wrangler/config-schema.json"
name = "flutterkaigi-2025-website"
main = "web/index.js"
compatibility_date = "2025-04-23"

[assets]
directory = "./build"
binding = "STATIC"

[route]
custom_domain = true
pattern = "2025.flutterkaigi.jp"
