"$schema" = "node_modules/wrangler/config-schema.json"
name = "flutterkaigi-2025-website"
account_id = "cdd8f59359fe226645e7b541cdc53b57"
main = "bin/main.js"
compatibility_date = "2025-04-23"

[assets]
directory = "./build/jaspr"
binding = "STATIC"

[route]
custom_domain = true
pattern = "2025.flutterkaigi.jp"
