"$schema" = "node_modules/wrangler/config-schema.json"
name = "flutterkaigi-2025-website"
main = "web/index.js"
compatibility_date = "2025-04-23"

[assets]
directory = "./build/jaspr"
binding = "STATIC"
not_found_handling = "404-page"

[route]
custom_domain = true
pattern = "2025.flutterkaigi.jp"
