"$schema" = "node_modules/wrangler/config-schema.json"
name = "flutterkaigi-2025-conference-app"
account_id = "cdd8f59359fe226645e7b541cdc53b57"
main = "bin/main.js"
compatibility_date = "2025-04-23"
preview_urls = true

[assets]
directory = "./build/web"
binding = "ASSETS"
not_found_handling = "single-page-application"

[route]
custom_domain = true
pattern = "2025-app.flutterkaigi.jp"
