name: flutterkaigi_lints
publish_to: none

resolution: workspace

environment:
  sdk: ^3.7.2
  flutter: ^3.29.2

dependencies:
  altive_lints: ^1.19.1
  custom_lint: ^0.7.5
  flutter:
    sdk: flutter
