name: Check Spell

on:
  pull_request:

jobs:
  check-spell:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Read .tool-versions
        uses: marocchino/tool-versions-action@18a164fa2b0db1cc1edf7305fcb17ace36d1c306 # v1.2.0
        id: versions
      - name: Setup bun
        uses: oven-sh/setup-bun@4bc047ad259df6fc24a6c9b0f9a0cb08cf17fbe5 # v2.0.1
        with:
          bun-version: ${{ steps.versions.outputs.bun }}
      - name: Install dependencies
        run: bun install --frozen-lockfile
      - name: Run spell check
        run: bunx cspell .
