name: Check Pull Request

on:
  pull_request:

concurrency:
  group: check-pr-${{ github.ref }}
  cancel-in-progress: true

jobs:
  changes:
    uses: ./.github/workflows/wc-check-changes.yaml

  skip-job-no-changes:
    runs-on: ubuntu-24.04
    needs: changes
    if: ${{ needs.changes.outputs.any == 'false'}}
    steps:
      # https://github.com/peter-evans/create-or-update-comment
      - name: Skip comment
        uses: peter-evans/create-or-update-comment@71345be0265236311c031f5c7866368bd1eff043 # v4.0.0
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            チェック対象ファイルに変更がないため、ジョブの実行をスキップしました。

  check-spell:
    needs: changes
    if: ${{ needs.changes.outputs.spell == 'true' }}
    uses: ./.github/workflows/wc-check-spell.yaml 

  status-check:
    runs-on: ubuntu-24.04
    needs:
      - check-spell
    permissions: {}
    if: failure()
    steps:
      - run: exit 1 
