name: "Sync GitHub Labels"

on:
  push:
    branches:
      - 'main'
    paths:
      - '.github/labels.yaml'
      - '.github/workflows/labels.yaml'
  pull_request:
    paths:
      - '.github/labels.yaml'
      - '.github/workflows/labels.yaml'

jobs:
  labels:
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      issues: write
    steps:
      # https://github.com/actions/checkout
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      # https://github.com/crazy-max/ghaction-github-labeler
      - name: Run Labeler
        uses: crazy-max/ghaction-github-labeler@24d110aa46a59976b8a7f35518cb7f14f434c916 # v5.3.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          yaml-file: .github/labels.yaml
          dry-run: ${{ github.event_name == 'pull_request' }}
