name: Test BFF Engine

on:
  pull_request:
    paths:
      - "bff/engine/**"
      - "packages/bff_client/**"
      - "packages/db_types/**"
  push:
    branches:
      - main
    paths:
      - "bff/engine/**"
      - "packages/bff_client/**"
      - "packages/db_types/**"
  workflow_dispatch:

concurrency:
  group: test-bff-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-24.04
    timeout-minutes: 10
    steps:
      # https://github.com/actions/checkout
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      # https://github.com/jdx/mise-action
      - name: Install Mise dependencies
        uses: jdx/mise-action@5083fe46898c414b2475087cc79da59e7da859e8 # v2.1.11
        with:
          install_args: "dart"

      - name: Get dependencies (packages/bff_client)
        working-directory: packages/bff_client
        run: dart pub get

      - name: Get dependencies (packages/db_types)
        working-directory: packages/db_types
        run: dart pub get

      - name: Get dependencies (bff/engine)
        working-directory: bff/engine
        run: dart pub get

      - name: Analyze (packages/bff_client)
        working-directory: packages/bff_client
        run: dart analyze --fatal-infos

      - name: Analyze (packages/db_types)
        working-directory: packages/db_types
        run: dart analyze --fatal-infos

      - name: Analyze (bff/engine)
        working-directory: bff/engine
        run: dart analyze --fatal-infos

      - name: Format check (packages/bff_client)
        working-directory: packages/bff_client
        run: dart format --output=none --set-exit-if-changed .

      - name: Format check (packages/db_types)
        working-directory: packages/db_types
        run: dart format --output=none --set-exit-if-changed .

      - name: Format check (bff/engine)
        working-directory: bff/engine
        run: dart format --output=none --set-exit-if-changed .

      - name: Test (packages/bff_client)
        working-directory: packages/bff_client
        run: dart test --coverage=coverage
        continue-on-error: true

      - name: Test (packages/db_types)
        working-directory: packages/db_types
        run: dart test --coverage=coverage
        continue-on-error: true

      - name: Test (bff/engine)
        working-directory: bff/engine
        run: dart test --coverage=coverage
        continue-on-error: true

  build:
    runs-on: ubuntu-24.04
    timeout-minutes: 15
    needs: test
    steps:
      # https://github.com/actions/checkout
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      # https://github.com/docker/setup-buildx-action
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@c47758b77c9736f4b2ef4073d4d51994fabfe349 # v3.7.1

      - name: Build Docker image (test build)
        uses: docker/build-push-action@4f58ea79222b3b9dc2c8bbdd6debcef730109a75 # v6.9.0
        with:
          context: bff/engine
          file: bff/engine/Dockerfile
          push: false
          tags: bff-engine:test
          cache-from: type=gha
          cache-to: type=gha,mode=max
          platforms: linux/amd64

      - name: Test Docker container
        run: |
          # Start the container in background
          docker run -d --name bff-test \
            -p 8080:8080 \
            -e SUPABASE_URL=https://test.supabase.co \
            -e SUPABASE_SERVICE_ROLE_KEY=test-key \
            bff-engine:test

          # Wait for container to start
          sleep 10

          # Test health endpoint
          curl -f http://localhost:8080/health || exit 1

          # Test main endpoint
          curl -f http://localhost:8080/ || exit 1

          # Stop container
          docker stop bff-test

      # https://github.com/thollander/actions-comment-pull-request
      - name: Comment PR success
        uses: thollander/actions-comment-pull-request@24bffb9b452ba05a4f3f77933840a6a841d1b32b # v3.0.1
        if: ${{ github.event_name == 'pull_request' && success() }}
        with:
          message: |
            ## ✅ BFF Engine Tests Passed
            
            🎉 All tests and build checks passed successfully!
            
            - ✅ Code analysis (dart analyze)
            - ✅ Code formatting (dart format)
            - ✅ Unit tests (dart test)
            - ✅ Docker build
            - ✅ Container health check
          comment-tag: test-bff-success

      # https://github.com/thollander/actions-comment-pull-request  
      - name: Comment PR failure
        uses: thollander/actions-comment-pull-request@24bffb9b452ba05a4f3f77933840a6a841d1b32b # v3.0.1
        if: ${{ github.event_name == 'pull_request' && failure() }}
        with:
          message: |
            ## ❌ BFF Engine Tests Failed
            
            Some tests or checks failed. Please review the workflow logs and fix the issues.
            
            **Failed job**: ${{ github.job }}
            **Commit**: ${{ github.sha }}
          comment-tag: test-bff-failure
