name: Check Changes

on:
  workflow_call:
    outputs:
      any:
        value: ${{ jobs.changes.outputs.any }}
      spell:
        value: ${{ jobs.changes.outputs.spell }}

permissions:
  contents: read
  pull-requests: read

jobs:
  changes:
    runs-on: ubuntu-24.04
    outputs:
      any: ${{ steps.filter.outputs.changes != '[]' }}
      spell: ${{ steps.filter.outputs.spell }}
      style-deno: ${{ steps.filter.outputs.style-deno }}
    steps:
      # https://github.com/actions/checkout
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      # https://github.com/dorny/paths-filter
      - name: Paths Changes Filter
        uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36 # v3.0.2
        id: filter
        with:
          filters: |
            spell:
              - "**/*.{md,yaml,yml,dart,ts,js}"
            style-deno:
              - "**/*.{md,yaml,yml,json,jsonc}"
